"""Property Display Metadata & Glossary Layer.

Provides local-only, deterministic human-readable labels, descriptions,
and usage guidance for known Obsidian YAML frontmatter properties.

Core Safety Rules:
- Canonical YAML Property Keys remain completely untouched and un-translated in
  the storage/engine layer (e.g. status, owner, due_date).
- Display labels are presentation-only: 狀態 (status) in zh-Hant, Status (status) in en.
- Unknown/custom properties safely fallback to canonical key without speculative AI guesses.
- Never used to enforce schemas; purely informative for human understanding.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any, Optional


@dataclass(frozen=True)
class PropertyGlossaryEntry:
    canonical_key: str
    label_zh: str
    label_en: str
    short_description_zh: str
    short_description_en: str
    long_description_zh: str
    long_description_en: str
    usage_hint_zh: str
    usage_hint_en: str
    typical_type: str
    typical_control: str
    examples: tuple[str, ...] = field(default_factory=tuple)

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        d["examples"] = list(self.examples)
        return d


# Deterministic built-in glossary catalog
_GLOSSARY_ENTRIES: tuple[PropertyGlossaryEntry, ...] = (
    PropertyGlossaryEntry(
        canonical_key="type",
        label_zh="類型",
        label_en="Type",
        short_description_zh="標記筆記或物件的實體分類型態。",
        short_description_en="Classifies the entity or note type.",
        long_description_zh="用於區分不同領域的管理對象，如專案、任務、設備、人員、概念、文獻等。",
        long_description_en="Used to distinguish management entities such as projects, tasks, equipment, persons, concepts, literature.",
        usage_hint_zh="適用於全庫所有結構化筆記，便於 Dataview 篩選與分類檢視。",
        usage_hint_en="Applicable across all structured notes for convenient querying and filtering.",
        typical_type="text",
        typical_control="select",
        examples=("project", "task", "equipment", "person", "meeting", "book", "article"),
    ),
    PropertyGlossaryEntry(
        canonical_key="status",
        label_zh="狀態",
        label_en="Status",
        short_description_zh="表示此項目目前所處的工作或生命週期狀態。",
        short_description_en="Indicates current workflow or lifecycle status.",
        long_description_zh="追蹤實體或任務的推進進度與運作狀況，例如進行中、暫停、已完成或已封存。",
        long_description_en="Tracks progress and operational health, such as active, on hold, completed, or archived.",
        usage_hint_zh="專案、任務、設備、文件流程追蹤。",
        usage_hint_en="Essential for projects, tasks, hardware status, and document workflows.",
        typical_type="text",
        typical_control="select",
        examples=("active", "in_progress", "on_hold", "done", "archived", "draft"),
    ),
    PropertyGlossaryEntry(
        canonical_key="owner",
        label_zh="負責人",
        label_en="Owner",
        short_description_zh="主要負責或主導此項目的人員或團隊。",
        short_description_en="Primary person or team responsible for this entity.",
        long_description_zh="指定所有權人，可填寫人員名稱或使用 [[Note Link]] 關聯人員實體筆記。",
        long_description_en="Specifies the accountable owner, either as plain text or as a [[Note Link]].",
        usage_hint_zh="專案主責人、設備保管人、流程負責人。",
        usage_hint_en="Project lead, equipment custodian, or process owner.",
        typical_type="text / link",
        typical_control="text input / note link",
        examples=("[[Johnway]]", "Dr. J", "Dev Team", "Operations"),
    ),
    PropertyGlossaryEntry(
        canonical_key="assignee",
        label_zh="指派對象",
        label_en="Assignee",
        short_description_zh="被指派執行此項任務或行動的執行人員。",
        short_description_en="Person assigned to execute this task or action.",
        long_description_zh="明確任務的當前執行者，通常用於具體行動清單或短期交辦事項。",
        long_description_en="Clarifies the direct implementer for specific action items or tasks.",
        usage_hint_zh="待辦事項、衝刺任務、工單指派。",
        usage_hint_en="Action items, sprint tasks, and ticket assignments.",
        typical_type="text / link",
        typical_control="text input / note link",
        examples=("[[Alice]]", "Bob", "QA Specialist"),
    ),
    PropertyGlossaryEntry(
        canonical_key="start_date",
        label_zh="開始日期",
        label_en="Start Date",
        short_description_zh="項目或任務正式啟動的日期。",
        short_description_en="Official start or commencement date.",
        long_description_zh="記錄專案啟動、活動開始或合約生效的起始時間戳記。",
        long_description_en="Records when a project, event, or contractual period begins.",
        usage_hint_zh="時程規劃、甘特圖檢視、活動紀錄。",
        usage_hint_en="Timeline scheduling, Gantt views, event logs.",
        typical_type="date",
        typical_control="date picker",
        examples=("2026-01-01", "2026-09-01"),
    ),
    PropertyGlossaryEntry(
        canonical_key="end_date",
        label_zh="結束日期",
        label_en="End Date",
        short_description_zh="項目正式結案或活動結束的日期。",
        short_description_en="Official conclusion or end date.",
        long_description_zh="記錄專案完工、活動結束或效期終止的具體日期。",
        long_description_en="Records project completion, event wrap-up, or period termination.",
        usage_hint_zh="專案收尾、週期統計、歷史紀錄。",
        usage_hint_en="Project wrap-up, cycle calculation, historical records.",
        typical_type="date",
        typical_control="date picker",
        examples=("2026-06-30", "2026-12-31"),
    ),
    PropertyGlossaryEntry(
        canonical_key="due_date",
        label_zh="截止日期",
        label_en="Due Date",
        short_description_zh="必須完成此任務或交付成果的期限日期。",
        short_description_en="Target deadline for completion or delivery.",
        long_description_zh="提供時限預警與優先級排序依據，防範工作延宕。",
        long_description_en="Provides deadline alerting and priority sorting to prevent delays.",
        usage_hint_zh="任務期限、發布里程碑、交付驗收期限。",
        usage_hint_en="Task deadlines, release milestones, delivery due dates.",
        typical_type="date",
        typical_control="date picker",
        examples=("2026-09-15", "2026-10-01"),
    ),
    PropertyGlossaryEntry(
        canonical_key="review_date",
        label_zh="檢視日期",
        label_en="Review Date",
        short_description_zh="預計重新審閱或評估此項目的日期。",
        short_description_en="Scheduled date for periodic review or re-evaluation.",
        long_description_zh="用於週期性回顧、書籍讀後複習、制度評估或架構健檢。",
        long_description_en="Used for recurring check-ins, reading review intervals, policy audits.",
        usage_hint_zh="定期回顧、閱讀筆記複習、安全架構健檢。",
        usage_hint_en="Periodic audits, reading spaced review, security posture checks.",
        typical_type="date",
        typical_control="date picker",
        examples=("2026-10-15", "2026-12-01"),
    ),
    PropertyGlossaryEntry(
        canonical_key="effective_date",
        label_zh="生效日期",
        label_en="Effective Date",
        short_description_zh="規章、架構規範或協議正式生效的日期。",
        short_description_en="Date when a policy, standard, or contract takes effect.",
        long_description_zh="確保政策版本與治理規則具備精確的時間界線。",
        long_description_en="Ensures governance rules and policies have precise temporal validity.",
        usage_hint_zh="治理規則、安全協議、標準作業程序 (SOP)。",
        usage_hint_en="Governance policies, security protocols, Standard Operating Procedures.",
        typical_type="date",
        typical_control="date picker",
        examples=("2026-01-01", "2026-09-01"),
    ),
    PropertyGlossaryEntry(
        canonical_key="expiry_date",
        label_zh="到期日期",
        label_en="Expiry Date",
        short_description_zh="授權、認證或合約終止效力的日期。",
        short_description_en="Date when a license, certificate, or agreement expires.",
        long_description_zh="自動預警即將失效的憑證、授權或硬體保固。",
        long_description_en="Provides automated warnings for expiring certs, licenses, or warranties.",
        usage_hint_zh="SSL 憑證、軟體授權、合約終止日。",
        usage_hint_en="TLS/SSL certificates, software subscriptions, contracts.",
        typical_type="date",
        typical_control="date picker",
        examples=("2027-01-01", "2026-12-31"),
    ),
    PropertyGlossaryEntry(
        canonical_key="priority",
        label_zh="優先級",
        label_en="Priority",
        short_description_zh="項目的緊急與重要程度評級。",
        short_description_en="Urgency and importance ranking for execution.",
        long_description_zh="引導工作排程與資源分配，通常分為高、中、低等層級。",
        long_description_en="Guides scheduling and resource allocation, typically High, Medium, Low.",
        usage_hint_zh="待辦排序、Issue 追蹤、衝刺規劃。",
        usage_hint_en="Backlog grooming, issue triaging, sprint planning.",
        typical_type="text",
        typical_control="select",
        examples=("high", "medium", "low", "urgent", "P1", "P2"),
    ),
    PropertyGlossaryEntry(
        canonical_key="progress",
        label_zh="進度百分比",
        label_en="Progress",
        short_description_zh="整體完成度百分比或階段指標。",
        short_description_en="Percentage completion or milestone progress.",
        long_description_zh="數值化呈現目標達成狀況，通常介於 0 至 100 之間。",
        long_description_en="Quantifies completion status, typically an integer between 0 and 100.",
        usage_hint_zh="里程碑推進、專案進度條、大型研究階段。",
        usage_hint_en="Milestone tracking, project progress bars, research stages.",
        typical_type="number",
        typical_control="number input",
        examples=("0", "25", "50", "80", "100"),
    ),
    PropertyGlossaryEntry(
        canonical_key="project",
        label_zh="所屬專案",
        label_en="Project",
        short_description_zh="此項目隸屬或關聯的主要專案名稱。",
        short_description_en="Primary project this entity belongs or relates to.",
        long_description_zh="用於將多篇分散的筆記、任務或文獻匯聚至單一專案核心。",
        long_description_en="Aggregates distributed notes, tasks, or literature under a single project.",
        usage_hint_zh="專案聚合、關聯分析、知識網絡構建。",
        usage_hint_en="Project aggregation, relationship mapping, PKM linking.",
        typical_type="text / link",
        typical_control="text input / note link",
        examples=("[[Obsidian Property Studio]]", "[[AI Engine]]", "PKM Redesign"),
    ),
    PropertyGlossaryEntry(
        canonical_key="related",
        label_zh="相關連結",
        label_en="Related",
        short_description_zh="其他具備語意關聯的筆記或實體清單。",
        short_description_en="List of semantically related notes or entities.",
        long_description_zh="構建雙向網狀連結，便於在探索主題時延伸閱讀。",
        long_description_en="Builds associative knowledge graphs for exploratory cross-reading.",
        usage_hint_zh="主題延伸、跨領域參照、筆記關聯分析。",
        usage_hint_en="Topic exploration, cross-domain references, relationship checks.",
        typical_type="list of links",
        typical_control="multi-select / tag input",
        examples=("['[[Architecture Guide]]', '[[Testing Strategy]]']", "['[[Project Alpha]]']"),
    ),
    PropertyGlossaryEntry(
        canonical_key="source",
        label_zh="資訊來源",
        label_en="Source",
        short_description_zh="引用的文獻、原始文章、會議或靈感出處。",
        short_description_en="Originating citation, source article, or reference.",
        long_description_zh="保留知識溯源資訊，可以是外部 URL、書籍名或內部來源筆記。",
        long_description_en="Preserves provenance information, such as external URLs, book titles, or source notes.",
        usage_hint_zh="文獻筆記、研究洞察、會議記錄摘要。",
        usage_hint_en="Literature notes, research findings, meeting minutes.",
        typical_type="text / link",
        typical_control="text input / url",
        examples=("https://obsidian.md", "[[Clean Architecture Book]]", "ArXiv:2401.00001"),
    ),
    PropertyGlossaryEntry(
        canonical_key="url",
        label_zh="外部網址",
        label_en="URL",
        short_description_zh="外部網站、API 或線上資源的完整超連結。",
        short_description_en="External hyperlink or resource endpoint.",
        long_description_zh="直接連結外部系統、文檔官網或遠端儲存庫。",
        long_description_en="Direct link to external websites, documentation, or remote repositories.",
        usage_hint_zh="外部文檔、工具首頁、線上儀表板。",
        usage_hint_en="External docs, tool landing pages, cloud dashboards.",
        typical_type="text (url)",
        typical_control="url input",
        examples=("https://github.com/SmartyJohnway/Obsidian-Property-Studio",),
    ),
    PropertyGlossaryEntry(
        canonical_key="author",
        label_zh="作者",
        label_en="Author",
        short_description_zh="文獻、書籍或原始內容的創作者。",
        short_description_en="Creator or author of the document or media.",
        long_description_zh="記錄創作者姓名，可使用字串或指向作者實體筆記的連結。",
        long_description_en="Records creator name, either as text or a link to author person notes.",
        usage_hint_zh="書籍、學術論文、部落格專欄、技術規範。",
        usage_hint_en="Books, academic papers, blog posts, RFCs.",
        typical_type="text / link",
        typical_control="text input / note link",
        examples=("Martin Fowler", "[[Gene Kim]]", "Dr. J"),
    ),
    PropertyGlossaryEntry(
        canonical_key="authors",
        label_zh="共同作者清單",
        label_en="Authors",
        short_description_zh="多位創作者或論文共同作者之陣列清單。",
        short_description_en="Array list of multiple authors or contributors.",
        long_description_zh="當文獻或專案由多人共同完成時，以列表格式記載所有作者。",
        long_description_en="Records multiple collaborators or co-authors in list format.",
        usage_hint_zh="多作者論文、聯合報告、開源社群貢獻名冊。",
        usage_hint_en="Multi-author papers, joint reports, contributor rosters.",
        typical_type="list",
        typical_control="multi-select / tag input",
        examples=("['Alice', 'Bob']", "['[[Author 1]]', '[[Author 2]]']"),
    ),
    PropertyGlossaryEntry(
        canonical_key="vendor",
        label_zh="供應廠商",
        label_en="Vendor",
        short_description_zh="提供設備、軟體或服務之外部供應商。",
        short_description_en="External supplier or service provider.",
        long_description_zh="管理企業採購關係、支援合約與廠商聯絡資訊。",
        long_description_en="Manages procurement relationships, support agreements, and vendor contacts.",
        usage_hint_zh="設備採購、雲端供應商、第三方服務評估。",
        usage_hint_en="Hardware assets, cloud providers, 3rd-party vendor reviews.",
        typical_type="text / link",
        typical_control="text input / note link",
        examples=("Dell", "Microsoft", "[[AWS]]", "[[ACME Corp]]"),
    ),
    PropertyGlossaryEntry(
        canonical_key="supplier",
        label_zh="進貨供應商",
        label_en="Supplier",
        short_description_zh="原物料或零件供應夥伴。",
        short_description_en="Supplier for raw materials or parts.",
        long_description_zh="追蹤物料進貨來源與供應鏈關係。",
        long_description_en="Tracks procurement origin and supply chain relationships.",
        usage_hint_zh="供應鏈管理、零件清冊、庫存來源。",
        usage_hint_en="Supply chain, spare parts catalog, inventory sources.",
        typical_type="text / link",
        typical_control="text input / note link",
        examples=("Fastenal", "[[Component Supplier A]]"),
    ),
    PropertyGlossaryEntry(
        canonical_key="manufacturer",
        label_zh="製造廠商",
        label_en="Manufacturer",
        short_description_zh="硬體或實體設備之原廠製造商 (OEM)。",
        short_description_en="Original Equipment Manufacturer (OEM).",
        long_description_zh="記載硬體製造原廠，方便查閱技術手冊與驅動程式支援。",
        long_description_en="Records OEM brand for spec lookups and warranty tracking.",
        usage_hint_zh="伺服器硬體、網路設備、實驗室儀器。",
        usage_hint_en="Server hardware, network devices, laboratory instruments.",
        typical_type="text",
        typical_control="text input",
        examples=("Apple", "Cisco", "HP Enterprise", "Sony"),
    ),
    PropertyGlossaryEntry(
        canonical_key="location",
        label_zh="存放位置 / 地點",
        label_en="Location",
        short_description_zh="實體資產放置地點或會議舉辦場所。",
        short_description_en="Physical asset placement or meeting venue.",
        long_description_zh="標記機房、辦公室、機架位置或地理座標。",
        long_description_en="Marks server racks, office rooms, or geographic facilities.",
        usage_hint_zh="固定資產盤點、現場維修導引、空間管理。",
        usage_hint_en="Asset inventory, on-site maintenance routing, facility management.",
        typical_type="text",
        typical_control="text input",
        examples=("Room 302", "Rack A-04", "Taipei HQ", "Cloud Region us-west-1"),
    ),
    PropertyGlossaryEntry(
        canonical_key="department",
        label_zh="所屬部門",
        label_en="Department",
        short_description_zh="負責管轄或使用此資產的組織部門。",
        short_description_en="Organizational unit owning or utilizing the asset.",
        long_description_zh="劃分跨部門權責、費用分攤與存取權限範圍。",
        long_description_en="Divides cross-departmental accountability and chargeback.",
        usage_hint_zh="組織架構分類、部門資產歸屬、審批流程。",
        usage_hint_en="Org hierarchy, departmental cost center, approval workflows.",
        typical_type="text",
        typical_control="select",
        examples=("Engineering", "R&D", "Finance", "Legal", "Human Resources"),
    ),
    PropertyGlossaryEntry(
        canonical_key="organisation",
        label_zh="組織單位",
        label_en="Organisation",
        short_description_zh="關聯之法人機構或組織實體。",
        short_description_en="Associated corporate entity or organization.",
        long_description_zh="標記專案或標準所屬的法人機構。",
        long_description_en="Labels the overarching organization or company.",
        usage_hint_zh="跨機構合作、產業聯盟、法團識別。",
        usage_hint_en="Cross-org partnerships, consortia, enterprise tracking.",
        typical_type="text / link",
        typical_control="text input / note link",
        examples=("W3C", "ISO", "[[OpenAI]]"),
    ),
    PropertyGlossaryEntry(
        canonical_key="organization",
        label_zh="組織單位",
        label_en="Organization",
        short_description_zh="關聯之法人機構或組織實體 (美式拼法)。",
        short_description_en="Associated corporate entity or organization.",
        long_description_zh="標記專案或標準所屬的法人機構。",
        long_description_en="Labels the overarching organization or company.",
        usage_hint_zh="跨機構合作、產業聯盟、法團識別。",
        usage_hint_en="Cross-org partnerships, consortia, enterprise tracking.",
        typical_type="text / link",
        typical_control="text input / note link",
        examples=("W3C", "ISO", "[[Google]]"),
    ),
    PropertyGlossaryEntry(
        canonical_key="version",
        label_zh="版本編號",
        label_en="Version",
        short_description_zh="軟體、規格書或文件的語意版本 (SemVer)。",
        short_description_en="Semantic version of software, spec, or document.",
        long_description_zh="追蹤版本迭代歷史，區分主要重大更新與修復版本。",
        long_description_en="Tracks iteration lifecycle and compatibility boundaries.",
        usage_hint_zh="軟體套件、API 規格、產品發布日誌。",
        usage_hint_en="Software packages, API specs, release manifests.",
        typical_type="text",
        typical_control="text input",
        examples=("1.0.0", "v1.1.0", "2.4.1-beta"),
    ),
    PropertyGlossaryEntry(
        canonical_key="revision",
        label_zh="修訂版本",
        label_en="Revision",
        short_description_zh="文件、架構設計或圖紙之內部修訂號碼。",
        short_description_en="Internal revision identifier for drawings or documents.",
        long_description_zh="用於正式工程圖紙、合約或規範的細部修訂標記。",
        long_description_en="Marks detailed engineering revisions for blueprints and contracts.",
        usage_hint_zh="硬體電路圖、合約修訂本、SOP 版次。",
        usage_hint_en="Hardware schematics, contract revisions, SOP drafts.",
        typical_type="text",
        typical_control="text input",
        examples=("Rev A", "Rev 2.1", "Draft 3"),
    ),
    PropertyGlossaryEntry(
        canonical_key="purchase_date",
        label_zh="採購日期",
        label_en="Purchase Date",
        short_description_zh="購入或訂購該資產的日期。",
        short_description_en="Date when the asset or item was purchased.",
        long_description_zh="用於折舊計算、保固計算起始點與採購核銷審計。",
        long_description_en="Used for asset depreciation, warranty start, and financial audits.",
        usage_hint_zh="固定資產管理、財務折舊、採購紀錄。",
        usage_hint_en="Fixed asset tracking, financial accounting, purchase records.",
        typical_type="date",
        typical_control="date picker",
        examples=("2025-06-15", "2026-03-01"),
    ),
    PropertyGlossaryEntry(
        canonical_key="cost",
        label_zh="費用 / 成本",
        label_en="Cost",
        short_description_zh="購入金額、授權費用或維護開銷。",
        short_description_en="Monetary purchase cost, license fee, or expense.",
        long_description_zh="紀錄財務支出數值，便於統計年度預算與總體持有成本 (TCO)。",
        long_description_en="Records monetary expenditures for budget tracking and TCO analysis.",
        usage_hint_zh="採購預算、訂閱花費、維修報銷清單。",
        usage_hint_en="Procurement budget, SaaS subscription cost, repair expense.",
        typical_type="number",
        typical_control="number input",
        examples=("1200", "45000", "99.99"),
    ),
    PropertyGlossaryEntry(
        canonical_key="maintenance_due",
        label_zh="保養維護期限",
        label_en="Maintenance Due",
        short_description_zh="下次預計進行保養或健康巡檢的日期。",
        short_description_en="Next scheduled maintenance or servicing date.",
        long_description_zh="預防性維護提醒，降低設備無預警故障風險。",
        long_description_en="Preventive maintenance scheduling to avoid downtime.",
        usage_hint_zh="儀器校正、伺服器巡檢、設備定檢。",
        usage_hint_en="Hardware calibration, server health checks, periodic inspection.",
        typical_type="date",
        typical_control="date picker",
        examples=("2026-11-30", "2027-03-15"),
    ),
    PropertyGlossaryEntry(
        canonical_key="last_service_date",
        label_zh="上次維護日期",
        label_en="Last Service Date",
        short_description_zh="最近一次完成檢修或保養的日期。",
        short_description_en="Most recent date the equipment was serviced.",
        long_description_zh="紀錄歷史維護履歷，確認保養週期合規性。",
        long_description_en="Maintains service history and ensures compliance intervals.",
        usage_hint_zh="維修履歷、保養紀錄、工單歷史。",
        usage_hint_en="Maintenance history, service logs, work orders.",
        typical_type="date",
        typical_control="date picker",
        examples=("2026-06-01", "2026-08-15"),
    ),
    PropertyGlossaryEntry(
        canonical_key="next_service_date",
        label_zh="下次維護日期",
        label_en="Next Service Date",
        short_description_zh="預定下次維修服務或原廠保養的日期。",
        short_description_en="Next scheduled service or maintenance inspection.",
        long_description_zh="安排定期巡檢與原廠年度維護合約。",
        long_description_en="Schedules recurring inspections and annual service contracts.",
        usage_hint_zh="設備定檢、原廠維護合約、保固巡檢。",
        usage_hint_en="Equipment checkups, OEM service plans, maintenance audits.",
        typical_type="date",
        typical_control="date picker",
        examples=("2026-12-01", "2027-06-01"),
    ),
    PropertyGlossaryEntry(
        canonical_key="serial_number",
        label_zh="序號 (S/N)",
        label_en="Serial Number",
        short_description_zh="硬體或產品出廠唯一識別碼 (S/N)。",
        short_description_en="Unique manufacturer serial number (S/N).",
        long_description_zh="精確辨識每台實體裝置，防範資產混淆並加速原廠報修。",
        long_description_en="Uniquely identifies individual hardware devices for warranty calls.",
        usage_hint_zh="IT 資產盤點、原廠保固登記、出入庫管理。",
        usage_hint_en="IT asset tracking, warranty claims, inventory audits.",
        typical_type="text",
        typical_control="text input",
        examples=("SN-9948201-A", "C02XYZ123456"),
    ),
    PropertyGlossaryEntry(
        canonical_key="category",
        label_zh="分類類別",
        label_en="Category",
        short_description_zh="廣義的主題分類或目錄群組。",
        short_description_en="Broad topic category or grouping.",
        long_description_zh="高層次的樹狀分類標籤，提供巨觀維度的分類瀏覽。",
        long_description_en="High-level classification grouping for macro-level organization.",
        usage_hint_zh="知識庫導覽、文章分類、資源索引。",
        usage_hint_en="Knowledge cataloging, resource indexing, library groups.",
        typical_type="text",
        typical_control="select",
        examples=("Architecture", "Machine Learning", "Governance", "DevOps"),
    ),
    PropertyGlossaryEntry(
        canonical_key="topics",
        label_zh="涵蓋主題",
        label_en="Topics",
        short_description_zh="此筆記涵蓋的主題標籤或研究領域清單。",
        short_description_en="List of covered topics or research domains.",
        long_description_zh="多維度的概念標註，便於跨目錄交叉檢索。",
        long_description_en="Multi-dimensional subject tags for cross-cutting queries.",
        usage_hint_zh="研究洞察、技術專題、靈感關聯。",
        usage_hint_en="Research topics, deep-dive subject tags, thematic queries.",
        typical_type="list",
        typical_control="multi-select / tag input",
        examples=("['PKM', 'YAML', 'Local-AI']", "['Database', 'Security']"),
    ),
    PropertyGlossaryEntry(
        canonical_key="tags",
        label_zh="標籤清單",
        label_en="Tags",
        short_description_zh="Obsidian 內建標籤陣列 (Frontmatter tags)。",
        short_description_en="Obsidian native frontmatter tags list.",
        long_description_zh="可被 Obsidian 標籤窗格檢索的標準標籤陣列，不需加 # 號。",
        long_description_en="Standard tags queryable in Obsidian tag pane, formatted without # prefix.",
        usage_hint_zh="輕量標記、臨時標籤、Obsidian 內建搜尋。",
        usage_hint_en="Lightweight tagging, ad-hoc metadata, native tag pane.",
        typical_type="list",
        typical_control="multi-select / tag input",
        examples=("['active', 'project', 'p1']", "['book-review', '2026']"),
    ),
    PropertyGlossaryEntry(
        canonical_key="repo",
        label_zh="儲存庫",
        label_en="Repository",
        short_description_zh="關聯之 Git 儲存庫名稱或路徑。",
        short_description_en="Linked Git repository name or path.",
        long_description_zh="連接 PKM 專案與程式碼庫，可填寫 repo 名稱或 GitHub 連結。",
        long_description_en="Bridges notes to software repositories, linking code to architecture.",
        usage_hint_zh="軟體專案、程式碼模組、開源工具。",
        usage_hint_en="Software components, code repositories, open-source projects.",
        typical_type="text / link",
        typical_control="text input / note link",
        examples=("SmartyJohnway/Obsidian-Property-Studio", "[[Repo-Obsidian-Property-Studio]]"),
    ),
    PropertyGlossaryEntry(
        canonical_key="repository",
        label_zh="程式碼儲存庫 (完整)",
        label_en="Repository (Full)",
        short_description_zh="完整 Git 儲存庫 URL 或識別名。",
        short_description_en="Full Git repository URL or identifier.",
        long_description_zh="提供遠端 Git 倉庫的完整定址。",
        long_description_en="Provides full addressing for remote Git repositories.",
        usage_hint_zh="CI/CD 配置、部署腳本關聯、軟體資產清冊。",
        usage_hint_en="CI/CD specs, deployment pipelines, software catalog.",
        typical_type="text (url)",
        typical_control="url input",
        examples=("https://github.com/SmartyJohnway/Obsidian-Property-Studio.git",),
    ),
    PropertyGlossaryEntry(
        canonical_key="software",
        label_zh="使用軟體 / 工具",
        label_en="Software",
        short_description_zh="執行此工作或本系統所依賴的軟體套件。",
        short_description_en="Software package or application relied upon.",
        long_description_zh="紀錄技術棧與工具鏈依賴。",
        long_description_en="Records technology stack and toolchain dependencies.",
        usage_hint_zh="技術棧紀錄、依賴分析、環境設定手冊。",
        usage_hint_en="Tech stack records, dependency audits, setup guides.",
        typical_type="text / link",
        typical_control="text input / note link",
        examples=("Python 3.13", "Obsidian", "Docker", "[[Tool-Pytest]]"),
    ),
    PropertyGlossaryEntry(
        canonical_key="tool",
        label_zh="專用工具",
        label_en="Tool",
        short_description_zh="指定使用的輔助工具或命令列程式。",
        short_description_en="Specific utility or command-line tool.",
        long_description_zh="記錄具體工具或輔助腳本。",
        long_description_en="Records specific utilities or automation scripts.",
        usage_hint_zh="工具鏈清單、效能測試工具、日常腳本。",
        usage_hint_en="Toolchains, benchmarking utilities, maintenance scripts.",
        typical_type="text / link",
        typical_control="text input / note link",
        examples=("uv", "ripgrep", "pytest"),
    ),
    PropertyGlossaryEntry(
        canonical_key="workflow",
        label_zh="工作流程",
        label_en="Workflow",
        short_description_zh="關聯之標準作業流程或工作流名稱。",
        short_description_en="Associated standard workflow or pipeline name.",
        long_description_zh="將實體或任務映射至標準流程節點。",
        long_description_en="Maps entities or tasks to formal workflow stages.",
        usage_hint_zh="SOP 參照、自動化管線、驗收流程。",
        usage_hint_en="SOP references, automation pipelines, review procedures.",
        typical_type="text / link",
        typical_control="text input / note link",
        examples=("Release-Closure-v1.1.0", "[[Workflow-Sprint-Review]]"),
    ),
    PropertyGlossaryEntry(
        canonical_key="jurisdiction",
        label_zh="適用法域 / 轄區",
        label_en="Jurisdiction",
        short_description_zh="法規、政策或標準所適用的法律轄區或管轄權。",
        short_description_en="Legal jurisdiction or regulatory domain governing this entity.",
        long_description_zh="合規治理專用，標註適用之國家、地區或監管機關。",
        long_description_en="Compliance metadata specifying governing countries or agencies.",
        usage_hint_zh="合規性檢查、隱私政策 (GDPR/CCPA)、資安法規。",
        usage_hint_en="Regulatory compliance, privacy laws (GDPR), security audits.",
        typical_type="text",
        typical_control="select",
        examples=("Taiwan", "EU", "Global", "US-Fed"),
    ),
    PropertyGlossaryEntry(
        canonical_key="applicability",
        label_zh="適用範圍",
        label_en="Applicability",
        short_description_zh="政策、架構準則或約定的生效適用對象範圍。 ",
        short_description_en="Scope of applicability for policies or standards.",
        long_description_zh="定義規範適用的團隊、系統或專案層級。",
        long_description_en="Defines target teams, systems, or tiers under scope.",
        usage_hint_zh="架構治理原則、安全準則、團隊規範。",
        usage_hint_en="Architecture principles, security guidelines, team standards.",
        typical_type="text",
        typical_control="select",
        examples=("All Projects", "Backend Only", "Production"),
    ),
    PropertyGlossaryEntry(
        canonical_key="compliance_status",
        label_zh="合規審查狀態",
        label_en="Compliance Status",
        short_description_zh="安全評估或法規合規之審查結果。",
        short_description_en="Result or state of compliance and security audit.",
        long_description_zh="追蹤系統是否符合 ISO 27001、SOC 2 或內部資安基準。",
        long_description_en="Tracks adherence to ISO 27001, SOC 2, or security baselines.",
        usage_hint_zh="資安審計、隱私評估、內部控制。",
        usage_hint_en="Security audits, privacy assessments, internal controls.",
        typical_type="text",
        typical_control="select",
        examples=("compliant", "non_compliant", "pending_review", "exempt"),
    ),
    PropertyGlossaryEntry(
        canonical_key="title",
        label_zh="自訂標題",
        label_en="Title",
        short_description_zh="筆記或實體的完整名稱或顯示標題。",
        short_description_en="Full display title or formal headline.",
        long_description_zh="當筆記檔名受限於系統命名規範時，可在 frontmatter 定義完整標題。",
        long_description_en="Provides a full human-readable title when filename is constrained.",
        usage_hint_zh="文章標題、發布文件、學術簡報。",
        usage_hint_en="Article titles, published papers, presentation decks.",
        typical_type="text",
        typical_control="text input",
        examples=("Obsidian Property Studio v1.1.0 Architecture Specification",),
    ),
    PropertyGlossaryEntry(
        canonical_key="description",
        label_zh="摘要說明",
        label_en="Description",
        short_description_zh="筆記或實體的簡短描述與核心摘要。",
        short_description_en="Brief summary or description of the note.",
        long_description_zh="提供一行至數行的簡短綱要，便於在清單或卡片中快速預覽。",
        long_description_en="One-to-two line synopsis for quick card previews and table listings.",
        usage_hint_zh="卡片預覽、搜尋摘要、專案簡介。",
        usage_hint_en="Card previews, search snippets, project overviews.",
        typical_type="text",
        typical_control="textarea",
        examples=("A local-first, zero-telemetry Property governance workspace for Obsidian.",),
    ),
    PropertyGlossaryEntry(
        canonical_key="aliases",
        label_zh="筆記別名 (Aliases)",
        label_en="Aliases",
        short_description_zh="Obsidian 內建支援的別名清單，供雙向連結自動搜尋匹配。",
        short_description_en="Obsidian native alias array for wikilink matching.",
        long_description_zh="設定別名後，在 Obsidian 內輸入 [[別名]] 可自動指向此筆記。",
        long_description_en="Allows linking to this note via alternative terms or abbreviations.",
        usage_hint_zh="縮寫、英文/中文對照名稱、舊版名稱相容。",
        usage_hint_en="Acronyms, multilingual names, legacy terms.",
        typical_type="list",
        typical_control="multi-select / tag input",
        examples=("['OPS', 'Property Studio', '屬性工作室']",),
    ),
    PropertyGlossaryEntry(
        canonical_key="created",
        label_zh="建立時間",
        label_en="Created At",
        short_description_zh="此筆記或資料最初被建立的時間戳記。",
        short_description_en="Initial creation timestamp for the record.",
        long_description_zh="紀錄資料誕生時間，輔助時間軸排序與生命週期追蹤。",
        long_description_en="Records initial creation time for chronological sorting.",
        usage_hint_zh="建立時間追蹤、日誌時間軸、歷史索引。",
        usage_hint_en="Creation date tracking, timeline sorting, history logs.",
        typical_type="date / datetime",
        typical_control="datetime picker",
        examples=("2026-09-01", "2026-09-01T12:00:00Z"),
    ),
    PropertyGlossaryEntry(
        canonical_key="updated",
        label_zh="更新時間",
        label_en="Updated At",
        short_description_zh="最後一次實質修改此內容的時間戳記。",
        short_description_en="Timestamp of most recent substantive update.",
        long_description_zh="確認知識的新鮮度與最後校驗時間。",
        long_description_en="Confirms freshness and last verification timestamp.",
        usage_hint_zh="文檔維護、新鮮度評估、過期預警。",
        usage_hint_en="Document freshness, maintenance alerts, recent updates.",
        typical_type="date / datetime",
        typical_control="datetime picker",
        examples=("2026-09-02", "2026-09-02T12:00:00Z"),
    ),
)

PROPERTY_GLOSSARY: dict[str, PropertyGlossaryEntry] = {
    e.canonical_key.casefold(): e for e in _GLOSSARY_ENTRIES
}
BUILTIN_PROPERTY_GLOSSARY = PROPERTY_GLOSSARY


def get_property_glossary_entry(key: str) -> Optional[PropertyGlossaryEntry]:
    """Retrieve glossary metadata for a canonical key, case-insensitively."""
    if not key:
        return None
    return PROPERTY_GLOSSARY.get(key.strip().casefold())


def get_property_display_label(
    key: str,
    lang: str = "zh-Hant",
    locale: str | None = None,
) -> str:
    """Format human-readable presentation label: e.g. 狀態 (status) in zh-Hant.

    For unknown/custom properties, safely returns the canonical key unchanged.
    """
    cleaned = key.strip()
    entry = get_property_glossary_entry(cleaned)
    if not entry:
        return cleaned

    effective_lang = locale or lang
    is_en = str(effective_lang).lower().startswith("en")
    label = entry.label_en if is_en else entry.label_zh
    if not label or label.strip() == entry.canonical_key:
        return entry.canonical_key
    return f"{label} ({entry.canonical_key})"



def export_glossary_catalog() -> dict[str, dict[str, Any]]:
    """Export all glossary entries as a dict for API delivery to the client UI."""
    return {k: e.to_dict() for k, e in PROPERTY_GLOSSARY.items()}

